name: Update GitHub Pages Documentation

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.x
        
    - name: Install DocFX
      run: dotnet tool install --global docfx
    
    - name: Verify docfx.json
      run: |
        echo "Checking for docfx.json"
        ls -R # Lista todos los archivos para ver dónde está docfx.json

    - name: Generate Documentation
      run: |
        cd TEG-api # Asegúrate de estar en la carpeta que contiene docfx.json
        docfx metadata
        docfx build
    - name: List generated files
      run: |
        echo "Listing _site directory:"
        ls -R _site
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _site
