name: Update GitHub Pages Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.x
        
    - name: Install DocFX
      run: dotnet tool install --global docfx

    - name: Generate Documentation
      run: |
        echo "Generating metadata..."
        docfx metadata
        echo "Building documentation..."
        docfx build
      working-directory: ./TEG-api

    - name: Checkout GitHub Pages Branch
      run: git fetch origin gh-pages && git checkout gh-pages
      working-directory: gh-pages

    - name: Copy Custom Home Page
      run: |
        echo "Copying custom index.html from gh-pages branch..."
        cp ./custom/index.html ./TEG-api/_site/index.html

    - name: Publish to GitHub Pages
      if: github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./TEG-api/_site
